### ISSUE TITLE
Implement Spring Security

### ISSUE THREAD

**Issue by Anirban-Chand** [Anirban-Chand/SpringBoot-CRUD-App#2]
- star the repo
- fork it
- clone in your local machine & create a new branch
- create a folder named "security" in src->main->java->com->example->firstproject
- implement spring security here
- commit & push

**Comment by javamultiplex** [comment]
@Anirban-Chand  - I would like to work on this. Can you please assign to me?

**Comment by srikantvs26** [comment]
I'm working on this.

**Comment by Anirban-Chand** [comment]
You both can work on this

**Comment by srikantvs26** [comment]
Hi @Anirban-Chand ,

Spring Security is implemented in commit id : b0232f8ebf109d4751356dd8e22684e3a866bbdc
