### ISSUE TITLE
Updating application.properties File

### ISSUE THREAD

**Issue by shreya5653** [Anirban-Chand/SpringBoot-CRUD-App#5]
Enhancing the application.properties file will make your application more maintainable and ready for future extensions, such as database integration. Updating the application.properties file ensures that future integration with databases or other external services can be done seamlessly. The pre-defined placeholders make the transition smoother and prevent disruptions in the development workflow.

**Comment by shreya5653** [comment]
I want to work on this issue. Please assign it to me

**Comment by Anirban-Chand** [comment]
Hi @shreya5653,

Glad to see your interest in this repo.
But unfortunately, I'm not maintaining the repo anymore.
